/** Screens captured from Codex v0.159.2 in tmux (100×40), paths shortened. */
export const CODEX_TRUST_SCREEN = [
  "  Folder access",
  "  /tmp/demo",
  "  /scratchpad/codexprompt.ua3k",
  "",
  "  Trust this folder? Codex can read, edit, and run files here, subject to your permission",
  "  settings. Folder settings can run code automatically, even without a model request. Continue",
  "  only if you trust these files. Your trust decision will be saved.",
  "",
  "› 1. Trust and continue",
  "  2. Back to Agent Command Center",
  "",
  "  enter continue · esc back"
].join("\n");

export const CODEX_APPROVAL_SCREEN = [
  "  >_ OpenAI Codex (v0.159.2)",
  "     /tmp/…/scratchpad/codexprompt.ua3k",
  "",
  "  Shall we turn “huh?” into “aha!”?",
  "",
  "",
  "› Create an empty file named hello.txt in this folder with the shell command touch hello.txt",
  "",
  "",
  "• I’ll create hello.txt in this folder.",
  "",
  "• Running touch hello.txt",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "  Would you like to run the following command?",
  "",
  "  Environment: local",
  "",
  "  Reason: Allow creating hello.txt in this folder? The workspace is read-only, so this command",
  "  requires write permission.",
  "",
  "  $ touch hello.txt",
  "",
  "",
  "› 1. Yes, proceed (y)",
  "  2. Yes, and don't ask again for commands that start with `touch hello.txt` (p)",
  "  3. No, and tell Codex what to do differently (esc)",
  "",
  "  Press enter to confirm or esc to cancel"
].join("\n");
