package journal

import (
	"encoding/json"
	"path/filepath"
	"strings"
	"testing"
)

var injectedMarkers = []string{
	"local-command-caveat", "command-name", "command-message", "local-command-stdout", "system-reminder",
	"task-notification", "Request interrupted", "No response requested", "Summary of earlier work",
	"Base directory for this skill", "AGENTS.md", "Agent notes body", "environment_context", "turn_aborted",
	"codex_internal_context", "active thread goal", "question_reply", "questionItemId", "Which computer",
}

func assertNoInjected(t *testing.T, value any) {
	t.Helper()
	encoded, _ := json.Marshal(value)
	for _, marker := range injectedMarkers {
		if strings.Contains(string(encoded), marker) {
			t.Fatalf("injected %q leaked: %s", marker, encoded)
		}
	}
}

func claudeUser(content any, flags map[string]any) map[string]any {
	line := map[string]any{"type": "user", "message": map[string]any{"role": "user", "content": content}}
	for key, value := range flags {
		line[key] = value
	}
	return line
}

func writeInjectedClaudeTranscript(t *testing.T) (*Reader, Ref) {
	t.Helper()
	root := t.TempDir()
	id := "12345678-abcd-4321-abcd-1234567890ab"
	writeLines(t, filepath.Join(root, "projects", "-tmp-pairfob", id+".jsonl"),
		claudeUser("<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>", map[string]any{"isMeta": true}),
		claudeUser("<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>", nil),
		claudeUser("<local-command-stdout>Set model to Opus</local-command-stdout>", nil),
		claudeUser([]map[string]any{
			{"type": "text", "text": "why does it reconnect?"},
			{"type": "text", "text": "<system-reminder>\nTodo list is empty.\n</system-reminder>"},
		}, nil),
		claudeUser([]map[string]any{{"type": "text", "text": "Base directory for this skill: /tmp/skill"}}, map[string]any{"isMeta": true}),
		map[string]any{"type": "assistant", "message": map[string]any{"role": "assistant", "content": []map[string]any{
			{"type": "tool_use", "id": "toolu_1", "name": "Read", "input": map[string]any{"file_path": "/tmp/a"}},
		}}},
		claudeUser([]map[string]any{{"type": "tool_result", "tool_use_id": "toolu_1", "content": "file body\n\n<system-reminder>\nConsider malware.\n</system-reminder>"}}, nil),
		claudeUser("<task-notification>\n<task-id>b1</task-id>\n</task-notification>", nil),
		claudeUser([]map[string]any{{"type": "text", "text": "[Request interrupted by user]"}}, nil),
		map[string]any{"type": "assistant", "message": map[string]any{"role": "assistant", "model": "<synthetic>", "content": []map[string]any{
			{"type": "text", "text": "No response requested."},
		}}},
		claudeUser("Summary of earlier work", map[string]any{"isCompactSummary": true, "isVisibleInTranscriptOnly": true}),
		claudeUser("<bash-input>git status</bash-input>", nil),
		claudeUser("<bash-stdout>clean</bash-stdout><bash-stderr></bash-stderr>", nil),
		claudeUser("<command-message>model</command-message>\n<command-name>/model</command-name>\n<command-args>opus</command-args>", nil),
		map[string]any{"type": "assistant", "message": map[string]any{"role": "assistant", "model": "claude", "content": []map[string]any{
			{"type": "text", "text": "Because the session expired."},
		}}},
	)
	return &Reader{ClaudeRoot: root}, Ref{Source: "herdr:claude", Agent: "claude", Kind: "id", Value: id}
}

func TestClaudeTraceShowsOnlyTypedPromptsAndAgentOutput(t *testing.T) {
	reader, ref := writeInjectedClaudeTranscript(t)
	page, err := reader.ReadTrace(ref, nil, 50)
	if err != nil {
		t.Fatal(err)
	}
	want := []Event{
		{Type: "user", Text: "/clear"},
		{Type: "user", Text: "why does it reconnect?"},
		{Type: "tool", Name: "Read", Input: `{"file_path":"/tmp/a"}`, Output: "file body"},
		{Type: "user", Text: "! git status"},
		{Type: "user", Text: "/model opus"},
		{Type: "assistant", Text: "Because the session expired."},
	}
	if len(page.Items) != len(want) {
		t.Fatalf("items=%+v", page.Items)
	}
	for i, item := range page.Items {
		if item.Type != want[i].Type || item.Text != want[i].Text || item.Name != want[i].Name || item.Input != want[i].Input || item.Output != want[i].Output {
			t.Fatalf("item %d=%+v want %+v", i, item, want[i])
		}
	}
	assertNoInjected(t, page)

	summary, err := reader.ReadTraceSummary(ref, nil, 50)
	if err != nil {
		t.Fatal(err)
	}
	detail, err := reader.ReadTraceDetail(ref, summary.Items[2].DetailRef)
	if err != nil || detail.Output != "file body" {
		t.Fatalf("detail=%+v err=%v", detail, err)
	}
}

func TestClaudeHistoryShowsOnlyTypedPromptsAndAgentOutput(t *testing.T) {
	reader, ref := writeInjectedClaudeTranscript(t)
	page, err := reader.Read(ref, nil, 50)
	if err != nil {
		t.Fatal(err)
	}
	texts := make([]string, 0, len(page.Messages))
	for _, message := range page.Messages {
		texts = append(texts, message.Role+":"+message.Text)
	}
	got := strings.Join(texts, "|")
	if got != "user:/clear|user:why does it reconnect?|assistant:工具 · Read|user:! git status|user:/model opus|assistant:Because the session expired." {
		t.Fatalf("history=%q", got)
	}
	assertNoInjected(t, page)
}

func TestClaudeMetaRecordsAreNotTaskActivity(t *testing.T) {
	line, _ := json.Marshal(claudeUser("<local-command-caveat>Caveat</local-command-caveat>", map[string]any{"isMeta": true}))
	if activity := scanActivity("claude", append(line, '\n'), 0); activity.Key != "" {
		t.Fatalf("meta record counted as activity: %+v", activity)
	}
}

func TestCodexDropsTheWholeInjectedAgentsFile(t *testing.T) {
	root := t.TempDir()
	id := "session_12345678"
	agents := "# AGENTS.md instructions for /tmp/repo\n\n<INSTRUCTIONS>\n# Agent notes\n\nAgent notes body\n\n## Section\n\nMore rules\n</INSTRUCTIONS>"
	writeLines(t, filepath.Join(root, "sessions", "2026", "10", "03", "rollout-"+id+".jsonl"),
		map[string]any{"type": "response_item", "payload": map[string]any{
			"type": "message", "role": "user", "content": []map[string]any{
				{"type": "input_text", "text": agents},
				{"type": "input_text", "text": "<environment_context>\n  <cwd>/tmp</cwd>\n</environment_context>"},
			},
		}},
		map[string]any{"type": "response_item", "payload": map[string]any{
			"type": "message", "role": "user", "content": []map[string]any{
				{"type": "input_text", "text": "<turn_aborted>\nThe user interrupted.\n</turn_aborted>"},
			},
		}},
		map[string]any{"type": "response_item", "payload": map[string]any{
			"type": "message", "role": "user", "content": []map[string]any{
				{"type": "input_text", "text": "<codex_internal_context source=\"goal\">\nContinue working toward the active thread goal.\n</codex_internal_context>"},
			},
		}},
		map[string]any{"type": "response_item", "payload": map[string]any{
			"type": "message", "role": "user", "content": []map[string]any{{"type": "input_text", "text": "fix the bug"}},
		}},
		map[string]any{"type": "response_item", "payload": map[string]any{
			"type": "message", "role": "user", "content": []map[string]any{{"type": "input_text", "text": "<send_user_message_question_reply>\n" +
				`[{"answer":"this Mac","question":"Which computer?","questionItemId":"[\"request_user_input_async\",\"call_1\",0]"}]` +
				"\n</send_user_message_question_reply>\n"}},
		}},
	)
	reader := &Reader{CodexRoot: root}
	ref := Ref{Source: "herdr:codex", Agent: "codex", Kind: "id", Value: id}
	trace, err := reader.ReadTrace(ref, nil, 20)
	if err != nil || len(trace.Items) != 2 || trace.Items[0].Text != "fix the bug" || trace.Items[1].Text != "this Mac" {
		t.Fatalf("trace=%+v err=%v", trace, err)
	}
	assertNoInjected(t, trace)
	history, err := reader.Read(ref, nil, 20)
	if err != nil || len(history.Messages) != 2 || history.Messages[0].Text != "fix the bug" || history.Messages[1].Text != "this Mac" {
		t.Fatalf("history=%+v err=%v", history, err)
	}
	assertNoInjected(t, history)
}

func TestClaudePastedTextKeepsBodyWithoutWrapper(t *testing.T) {
	text := "\n\n<pasted_content id=\"2c1f\">\nfirst line\n\nsecond\n</pasted_content id=\"2c1f\">\n\nreview it"
	if got := visibleClaudeUserText(text); got != "first line\n\nsecond\n\nreview it" {
		t.Fatalf("got %q", got)
	}
}

func TestStripTaggedBlocksKeepsUserText(t *testing.T) {
	cases := map[string]string{
		"see the <system-reminder> tag docs":                                         "see the <system-reminder> tag docs",
		"<system-reminder>\nunterminated user paste":                                 "<system-reminder>\nunterminated user paste",
		"keep\n<system-reminder>drop</system-reminder>\nthis":                        "keep\n\nthis",
		"<system-reminders>not ours</system-reminders>":                              "<system-reminders>not ours</system-reminders>",
		"  <system-reminder>a</system-reminder><system-reminder>b</system-reminder>": "  ",
	}
	for input, want := range cases {
		if got := stripTaggedBlocks(input, []string{"system-reminder"}); got != want {
			t.Fatalf("strip(%q)=%q want %q", input, got, want)
		}
	}
}

func TestInjectedTagsInsideTypedPromptsStayVisible(t *testing.T) {
	prompt := "Why does this render wrong?\n<command-name>/clear</command-name>\nplease fix"
	if event, ok := claudeUserEvent(prompt); !ok || event.Type != "user" || event.Text != prompt {
		t.Fatalf("command tags in a prompt: %+v", event)
	}
	shell := "Explain this fixture:\n<bash-input>ls</bash-input>"
	if event, ok := claudeUserEvent(shell); !ok || event.Type != "user" || event.Text != shell {
		t.Fatalf("bash tags in a prompt: %+v", event)
	}
	manifest := "Write a manifest like\n<skill>\n<name>x</name>\n</skill>\nthanks"
	if got := visibleCodexUserText(manifest); got != manifest {
		t.Fatalf("codex skill block in a prompt: %q", got)
	}
	injected := "<skill>\n<name>x</name>\n</skill>\n\nreal question"
	if got := visibleCodexUserText(injected); got != "real question" {
		t.Fatalf("leading injected skill: %q", got)
	}
}

func TestClaudeReminderOnlyToolResultStillCompletes(t *testing.T) {
	output := "<system-reminder>Warning: the file exists but the contents are empty.</system-reminder>"
	if got := visibleClaudeToolOutput(output); got != "Warning: the file exists but the contents are empty." {
		t.Fatalf("got %q", got)
	}
	if got := visibleClaudeToolOutput("body\n\n<system-reminder>x</system-reminder>"); got != "body" {
		t.Fatalf("got %q", got)
	}
}
