"""Bundle this local review into one offline HTML file; no dependencies."""
from pathlib import Path

root = Path(__file__).resolve().parent
html = (root / "review.template.html").read_text()
for marker, filename in {
    "/* REVIEW_CSS */": "review.css",
    "/* PROPOSALS_JS */": "proposals.js",
    "/* PROTOTYPES_JS */": "prototypes.js",
    "/* REVIEW_JS */": "review.js",
}.items():
    html = html.replace(marker, (root / filename).read_text())
html = html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by build.py; edit the source files beside this file. -->", 1)
(root / "index.html").write_text(html)
print(root / "index.html")
